# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bda2aaa2ff9cc20af623f6b8837d7af78f224e9cfd01460101e30f5655a4165e9e018729e0b770167aa2802856714df4c27410d117b304c626b3bf4b5232315b

test:
  secret_key_base: a44f019e3bc3142a6fd05a305ed9c6669961fd800e97ad5a618036bdfa8d63a43979b6804877fe3d41188bebe145fe782326983dcaeadaf9ec3298fdec6baf44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
